################################################################
# Projekt: BridgeSurfer
# Autor: Emanuel Vogt
# Organisation: 8gent.Harness
# Erstellt am: 2026-02-21
# Beschreibung: Docker-Compose Konfiguration f√ºr BridgeSurfer
# Lizenz: Alle Rechte vorbehalten
# Status: In Entwicklung
################################################################

version: '3.8'

services:
  bridgesurfer:
    build: .
    container_name: bridgesurfer_app
    ports:
      - "5027:5000"
    volumes:
      - ./data.json:/app/data.json
      - ./backups:/app/backups
      - ./debug_log.txt:/app/debug_log.txt
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
